// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gogin/internal/app/myapp02/biz"
	"gogin/internal/app/myapp02/conf"
	"gogin/internal/app/myapp02/data"
	"gogin/internal/app/myapp02/server"
	"gogin/internal/app/myapp02/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data) (*App, error) {
	dataData, err := data.NewData(confData)
	if err != nil {
		return nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, greeterService)
	grpcServer := server.NewGRPCServer(confServer, greeterService)
	app := newApp( httpServer, grpcServer)
	return app, nil
}
